### ISSUE TITLE
Note Classification

### ISSUE THREAD

**Issue by Hashem-Dylan** [Cornerback24/Python-Midi-Analysis#2]
When using the parser, I noticed the notes produced from Note.py were off by 1 octave when compared to the MIDI representation in a DAW (this case Garage Band). I adjusted the dictionary for Note values accordingly to reflect what is found in the DAW representation. 
<img width="376" alt="Screen Shot 2022-12-20 at 9 37 20 AM" src="https://user-images.githubusercontent.com/63964821/208708839-0032d03c-1aa9-491b-8b29-6b09937da50a.png">
<img width="1051" alt="PNG image" src="https://user-images.githubusercontent.com/63964821/208708949-ccafd56e-3721-4db4-92c0-5f4f0617dcf0.png">
`PITCH_DICTIONARY = {0: "C-2", 1: "C#-2", 2: "D-2", 3: "D#-2", 4: "E-2", 5: "F-2", 6: "F#-2",
                        7: "G-2", 8: "G#-2", 9: "A-2", 10: "A#-2", 11: "B-2", 12: "C-1", 13: "C#-1",
                        14: "D-1", 15: "D#-1", 16: "E-1", 17: "F-1", 18: "F#-1", 19: "G-1",
                        20: "G#-1", 21: "A-1", 22: "A#-1", 23: "B-1", 24: "C0", 25: "C#0", 26: "D0",
                        27: "D#0", 28: "E0", 29: "F0", 30: "F#0", 31: "G0", 32: "G#0", 33: "A0", 34: "A#0",
                        35: "B0", 36: "C1", 37: "C#1", 38: "D1", 39: "D#1", 40: "E1", 41: "F1",
                        42: "F#1", 43: "G1", 44: "G#1", 45: "A1", 46: "A#1", 47: "B1", 48: "C2",
                        49: "C#2", 50: "D2", 51: "D#2", 52: "E2", 53: "F2", 54: "F#2", 55: "G2",
                        56: "G#2", 57: "A2", 58: "A#2", 59: "B2", 60: "C3", 61: "C#3", 62: "D3",
                        63: "D#3", 64: "E3", 65: "F3", 66: "F#3", 67: "G3", 68: "G#3", 69: "A3",
                        70: "A#3", 71: "B3", 72: "C4", 73: "C#4", 74: "D4", 75: "D#4", 76: "E4",
                        77: "F4", 78: "F#4", 79: "G4", 80: "G#4", 81: "A4", 82: "A#4", 83: "B4",
                        84: "C5", 85: "C#5", 86: "D5", 87: "D#5", 88: "E5", 89: "F5", 90: "F#5",
                        91: "G5", 92: "G#5", 93: "A5", 94: "A#5", 95: "B5", 96: "C6", 97: "C#6",
                        98: "D6", 99: "D#6", 100: "E6", 101: "F6", 102: "F#6", 103: "G6", 104: "G#6",
                        105: "A6", 106: "A#6", 107: "B6", 108: "C7", 109: "C#7", 110: "D7",
                        111: "D#7", 112: "E7", 113: "F7", 114: "F#7", 115: "G7", 116: "G#7",
                        117: "A7", 118: "A#7", 119: "B7", 120: "C8", 121: "C#8", 122: "D8",
                        123: "D#8", 124: "E8", 125: "F8", 126: "F#8", 127: "G8"}
`

**Comment by Cornerback24** [comment]
Oh interesting GarageBand uses C3 for middle C. Seems like programs will either use C3, C4, or C5. I'll add your dictionary and add the option to choose what middle C is.

**Comment by Cornerback24** [comment]
Pushed an update to change what is displayed for middle C. It should use your dictionary matching Garage Band with "C3":
`MidiData("midi_file.mid", "C3")`
